import { IIlionaPackages, IIlionaPackagesAbbreviated } from "../../models/IIlionaPackage";

export enum IlionaPackagesTypes {
    FETCH_ILIONA_PACKAGES_STARTED = "@@FETCH_ILIONA_PACKAGES_STARTED",
    FETCH_ILIONA_PACKAGES_SUCCESS = "@@FETCH_ILIONA_PACKAGES_SUCCESS",
    FETCH_ILIONA_PACKAGES_FAILURE = "@@FETCH_ILIONA_PACKAGES_FAILURE",

    FETCH_ILIONA_PACKAGE_DETAIL_STARTED = "@@FETCH_ILIONA_PACKAGE_DETAIL_STARTED",
    FETCH_ILIONA_PACKAGE_DETAIL_SUCCESS = "@@FETCH_ILIONA_PACKAGE_DETAIL_SUCCESS",
    FETCH_ILIONA_PACKAGE_DETAIL_FAILURE = "@@FETCH_ILIONA_PACKAGE_DETAIL_FAILURE",

    FETCH_ILIONA_INSTALL_PACKAGE_FAILURE = "@@FETCH_ILIONA_INSTALL_PACKAGE_FAILURE",
    FETCH_ILIONA_INSTALL_PACKAGE_STARTED = "@@FETCH_ILIONA_INSTALL_PACKAGE_STARTED",
    FETCH_ILIONA_INSTALL_PACKAGE_SUCCESS = "@@FETCH_ILIONA_INSTALL_PACKAGE_SUCCESS",
}

export type PackagesState = Readonly<{
    ilionaPackages: IIlionaPackagesAbbreviated[];
    selectedPackageDetail: IIlionaPackages[];
    errorMessage: string;
    isFetching: boolean;
    packageInstallSuccessful: boolean;
    packageInstallFailed: boolean;
}>
